#version: '3.8'
#
#services:
#  service_vod:
#    build:
#      context: ./path_to_service_vod_directory
#      dockerfile: Dockerfile
#    ports:
#      - "8301:8301"
#    networks:
#      - app-network
#    depends_on:
#      - mysql
#      - nacos
#
#  service_order:
#    build:
#      context: ./path_to_service_order_directory
#      dockerfile: Dockerfile
#    ports:
#      - "8302:8302"
#    networks:
#      - app-network
#    depends_on:
#      - mysql
#      - nacos
#
#  service_activity:
#    build:
#      context: ./path_to_service_activity_directory
#      dockerfile: Dockerfile
#    ports:
#      - "8303:8303"
#    networks:
#      - app-network
#    depends_on:
#      - mysql
#      - nacos
#
#  service_user:
#    build:
#      context: ./path_to_service_user_directory
#      dockerfile: Dockerfile
#    ports:
#      - "8304:8304"
#    networks:
#      - app-network
#    depends_on:
#      - mysql
#      - nacos
#
#  service_wechat:
#    build:
#      context: ./path_to_service_wechat_directory
#      dockerfile: Dockerfile
#    ports:
#      - "8305:8305"
#    networks:
#      - app-network
#    depends_on:
#      - mysql
#      - nacos
#
#  service_gateway:
#    build:
#      context: ./path_to_service_gateway_directory
#      dockerfile: Dockerfile
#    ports:
#      - "8333:8333"
#    networks:
#      - app-network
#    depends_on:
#      - mysql
#      - nacos
#
#networks:
#  app-network:
#    driver: bridge

version: '3'
services:
  service_gateway:
    container_name: service_gateway
    build: # 服务的 Docker 构建文件位置
      context: ./service_gateway
      dockerfile: Dockerfile
    ports:
      - "8333:8333"
    networks:
      - mynetwork

  service_vod:
    container_name: service_vod
    build:
      context: ./service/service_vod
      dockerfile: Dockerfile
    ports:
      - "8301:8301"
    networks:
      - mynetwork
    depends_on: # 本服务依赖的服务，控制启动先后顺序
      - service_gateway

  service_order:
    container_name: service_order
    build:
      context: ./service/service_order
      dockerfile: Dockerfile
    ports:
      - "8302:8302"
    networks:
      - mynetwork
    depends_on:
      - service_gateway

  service_activity:
    container_name: service_activity
    build:
      context: ./service/service_activity
      dockerfile: Dockerfile
    ports:
      - "8303:8303"
    networks:
      - mynetwork
    depends_on:
      - service_gateway


  service_user:
    container_name: service_user
    build:
      context: ./service/service_user
      dockerfile: Dockerfile
    ports:
      - "8304:8304"
    networks:
      - mynetwork
    depends_on:
      - service_gateway

  service_wechat:
    container_name: service_wechat
    build:
      context: ./service/service_wechat
      dockerfile: Dockerfile
    ports:
      - "8305:8305"
    networks:
      - mynetwork
    depends_on:
      - service_gateway

# 网络，不定义的话就是默认网络
networks:
  mynetwork: